builder:
  track: dev

labels:
  app: estafette-gke-preemptible-killer
  app-group: estafette-various
  team: estafette-team
  language: golang

version:
  semver:
    major: 1
    minor: 0
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master

stages:
  build:
    image: golang:1.10.2-alpine3.7
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - go test `go list ./... | grep -v /vendor/`
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake:
    image: docker:18.03.1-ce
    commands:
    - cp Dockerfile ./publish
    - cp /etc/ssl/certs/ca-certificates.crt ./publish
    - docker build -t estafette/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_BUILD_VERSION} ./publish

  push-to-docker-hub:
    image: docker:18.03.1-ce
    env:
      DOCKER_HUB_USERNAME: estafette.secret(ogLXmmnenJmOIFhD.HTmCog7nTq1ZyinDmjcAtewgBcfeooyPdQ==)
      DOCKER_HUB_PASSWORD: estafette.secret(TnICQh6mELiXtR9i.GJ9La6dtKMAPgO1R59T7FDsPVFWv2hmXYdLylbXi4Ju0r29g)
    commands:
    - docker login --username=${DOCKER_HUB_USERNAME} --password="${DOCKER_HUB_PASSWORD}"
    - docker push estafette/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_BUILD_VERSION}
    when:
      status == 'succeeded' &&
      branch == 'master' &&
      server == 'gocd'

  slack-notify:
    image: extensions/slack-build-status:dev
    webhook: estafette.secret(OmEDcjzDuiu0zP1i.lioIlGIhUXGs8YUtQHEshUOT1WLIHt4rrkn6xEBENWiRnngQ12DbrXMNMZo6GNwIabJh5Jn_SWJLm3RQN_1DimoNh5hdu1-hpZxJGNIF6WgC-61ivWFnuY8sQjbz)
    name: ${ESTAFETTE_LABEL_APP}
    channels:
    - '#build-status'
    when:
      status == 'failed'

releases:
  tooling:
  development:
  staging:
  production: