builder:
  track: dev

labels:
  app-group: estafette-controllers
  team: estafette-team
  language: golang

version:
  semver:
    major: 1
    minor: 3
    patch: 2
    labelTemplate: '{{branch}}-{{auto}}'
    releaseBranch: 1.3.2

stages:
  build:
    parallelStages:
      build:
        image: golang:1.18-alpine
        env:
          CGO_ENABLED: 0
          GOOS: linux
        commands:
        - go test `go list ./... | grep -v /vendor/`
        - go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - pkhanhbkhn
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        repositories:
        - estafette

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        repositories:
        - estafette

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - pkhanhbkhn
