apiVersion: apps/v1
kind: Deployment
metadata:
  name: preemptible-killer
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: preemptible-killer
      terminationGracePeriodSeconds: 300
      containers:
      - name: preemptible-killer
        image: estafette/estafette-gke-preemptible-killer:1.1.21
        ports:
        - name: prom-metrics
          containerPort: 9001
        env:
        - name: DRAIN_TIMEOUT
          value: "300"
        - name: INTERVAL
          value: "600"
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /metrics
            port: prom-metrics
          initialDelaySeconds: 30
          timeoutSeconds: 1
