{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "estafette-gke-preemptible-killer.fullname" . }}
  labels:
{{ include "estafette-gke-preemptible-killer.labels" . | indent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  verbs:
  - list
- apiGroups: [""] # "" indicates the core/v1 API group
  resources:
  - events
  verbs:
  - create
  - get
  - update
{{- end -}}
