{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "estafette-gke-preemptible-killer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-gke-preemptible-killer.labels" . | indent 4 }}
  {{- if .Values.secret.workloadIdentityServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.secret.workloadIdentityServiceAccount }}
  {{- end }}
{{- end -}}
